### ISSUE TITLE
What's going on with March?

### ISSUE THREAD

**Issue by benjaminjosephw** [Twipped/Kalendae#125] opened 2014-03-15 13:10 UTC
When selecting 30th March 2014, the 31st March is also selected. March seems to have a similar issue every year.

I haven't looked into this issue to see why this might be happening, but I thought I should flag it just incase this hasn't been spotted yet.

![screen shot 2014-03-15 at 12 33 37](https://f.cloud.github.com/assets/4534268/2428348/4d02ce40-ac42-11e3-8711-466bcf61da9d.png)![screen shot 2014-03-15 at 12 34 07](https://f.cloud.github.com/assets/4534268/2428347/4d0082fc-ac42-11e3-800d-32eb324d25dd.png)![screen shot 2014-03-15 at 12 34 22](https://f.cloud.github.com/assets/4534268/2428346/4cfd2d28-ac42-11e3-92fd-8e84c7eb5d34.png)![screen shot 2014-03-15 at 12 34 39](https://f.cloud.github.com/assets/4534268/2428345/4cfbffb6-ac42-11e3-9331-a259deeb385e.png)![screen shot 2014-03-15 at 12 34 55](https://f.cloud.github.com/assets/4534268/2428344/4cf89a92-ac42-11e3-8635-6384d26c8a67.png)

**Comment by abernix** [comment] 2015-11-16 17:14
Haven't looked (nor do I even use this plugin, actually, just stumbled upon this in searching for a calendar :smile:), but I'm guessing this happens because of a) Daylight Savings Time going into effect around that time every year, and b) London's immediate placement at GMT+0 rather than +/- at all.

**Comment by feiticeir0** [comment] 2018-02-26 10:39
I can confirm that this bug is still active as of 2018 - with the month of March . 
When selecting the 25th of march, the 26th is automatically selected. The reverse is also true - selecting 26th, 25th is also selected... My timezone is Europe/Lisbon (GMT)

**Comment by willdud** [comment] 2020-01-09 09:35
Replication: https://jsfiddle.net/sn4a3r6o/2/
Fix: https://jsfiddle.net/sn4a3r6o/3/
PR: https://github.com/Twipped/Kalendae/pull/229

**Comment by Twipped** [comment] 2020-01-09 21:11
Fixed in 20c3b383b, v1.0.0 is now released

**Closed by Twipped** 2020-01-09 21:11 UTC
Labels: confirmed bug
